name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

env:
  DOCKER_IMAGE: asyasun/ci-cd-test-go

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      # - name: Install golangci-lint
      #   run: |
      #     curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
      #     sudo mv ./bin/golangci-lint /usr/local/bin/

      - name: Run tests and generate coverage report
        run: |
          # go test -coverprofile=coverage.out ./...
          # # Исключаем main.go
          # grep -v "main.go" coverage.out > filtered.out
          # mv filtered.out coverage.out
          echo "Running go test..."
          go test -v -coverprofile=coverage.out ./...

          echo "Checking if coverage.out exists..."
          if [ ! -f coverage.out ]; then
            echo "❌ coverage.out not found! Something went wrong with the tests."
            exit 1
          fi

          echo "Excluding main.go from coverage..."
          grep -v "main.go" coverage.out > filtered.out
          mv filtered.out coverage.out
          echo "✅ coverage.out ready"

      - name: Check code coverage threshold
        run: |
          total=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $total%"
          threshold=80.0
          awk -v cov=$total -v thr=$threshold 'BEGIN {exit cov < thr ? 1 : 0}'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out


  docker-push:
    needs: [build-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Dockerfile
        run: test -f Dockerfile || (echo "Dockerfile not found!" && exit 1)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  release:
    needs: build-test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # mb
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
  